#!/bin/bash

###########################
# Comprobación de sha y md5 #
###########################

echo "Comprobación de sha y md5";
echo "Inicia el programa";

#Creación de funciones encargadas de realizar la comprobación del archivo
funcion_sha () {
	ruta_archivo=$1;
	clave_original=$(zenity --entry --title="Clave sha original" --text="Ingresa la clave sha original" --entry-text="Aquí la clave");
	#Manejo de error al ingresar la clave sha
	if [ $clave_original="" ]
	then
		$(zenity --error --title="Error al ingresar clave" --text="No puedo continuar sin la clave sha");
		exit 0;
	fi
	echo "Generando clave sha del archivo por favor espera esto puede tardar unos minutos (depende del peso del archivo)";
	clave_actual=$(echo "$(shasum $ruta_archivo)" | grep '[a-zA-Z0-9]* [^/]' | cut -f 1 -d ' '); 
	echo "clave_original = $clave_original";
	echo "clave_actual  = $clave_actual";
	if [ $clave_original = $clave_actual ] 
	then
		$(zenity --info --title="Resultado de comprobación sha" --text="Las claves coinciden la integridad de tu archivo no a sido violada\n\nclave_original = $clave_original\nclave_actual  = $clave_actual");
	else
			$(zenity --error	--title="Resultado de comprobación sha" --text="Las claves no coinciden la integridad de tu archivo a sido violada\n\nclave_original = $clave_original\nclave_actual  = $clave_actual");
	fi
}

funcion_md5 () {
	ruta_archivo=$1;
	clave_original=$(zenity --entry --title="Clave sha original" --text="Ingresa la clave sha original" --entry-text="Aquí la clave");
	#Manejo de error al ingresar la clave md5
	if [ $clave_original="" ]
	then
		$(zenity --error --title="Error al ingresar clave" --text="No puedo continuar sin la clave md5");
		exit 0;
	fi
	clave_actual=$(md5sum $ruta_archivo);
	echo "Generando clave md5 del archivo por favor espera esto puede tardar unos minutos (depende del peso del archivo)";
	clave_actual=$(echo "$(md5sum $ruta_archivo)" | grep '[a-zA-Z0-9]* [^/]' | cut -f 1 -d ' ');
	echo "clave_original = $clave_original";
	echo "clave_actual  = $clave_actual";
	if [ $clave_original = $clave_actual ] 
	then
		$(zenity --info --title="Resultado de comprobación md5" --text="Las claves coinciden la integridad de tu archivo no a sido violada\n\nclave_original = $clave_original\nclave_actual  = $clave_actual");
	else
			$(zenity --error	--title="Resultado de comprobación md5" --text="Las claves no coinciden la integridad de tu archivo a sido violada\n\nclave_original = $clave_original\nclave_actual  = $clave_actual");
	fi
}
 
#hacemos una selección del archivo del cual queremos comprobar su clave sha o md5

archivo=$(zenity --file-selection --title="Selecciona un archivo para comprobar su autenticidad");

#Manejo de error al no seleccionar un archivo
if [ $archivo="" ]
then
	$(zenity --error --title="Error de selección" --text="No puedo continuar sin la selección de un archivo");
	exit 0;
fi

#seleccionamos el tipo de comprobación a realizar sha o md5

sha_md5=$(zenity --list --title="Selección de tipo de comprobación" --text="¿Que tipo de comprobación deseas hacer?" --radiolist --column="radio" --column="opción" "1" "sha" "2" "md5");

#Creación de estructura case para decidir que proceso ejecutar

case $sha_md5 in
	"sha"|"sha")
		echo "Estas realizando una comprobación de integridad sha";
		funcion_sha $archivo ;;
	"md5"|"md5")
		echo "Estas realizando una comprobación de integridad md5";
		funcion_md5 $archivo ;;
	*)
		$(zenity --error --title="Error de selección" --text="Opción no valida por favor selecciona una por lo menos") ;;
esac

echo "Fin del programa";
